### ISSUE TITLE
File google-services.json mancante

### ISSUE THREAD

**Issue by RedsAnDev** [perno97/CloudOnDemand#7]
```
Error:Execution failed for task ':app:processDebugGoogleServices'.
> File google-services.json is missing. The Google Services Plugin cannot function without it. 
   Searched Location: 
  /Users/RAD/AndroidStudioProjects/CloudOnDemand/app/src/debug/google-services.json
  /Users/RAD/AndroidStudioProjects/CloudOnDemand/app/google-services.json
```
Da quello che ho capito, manca questo file: contiene la key associata a qualche account specifico? Se così fosse, serve un file `readme.md` da inserire al posto di quello attuale, in cui indicare le fasi per ottemperare a tale compito.

**Comment by MatteoTaba** [comment]
Creato readme

2017-07-24 14:25 GMT+02:00 Andrea Rossi <notifications@github.com>:
